apiVersion: v1
kind: Service
metadata:
  labels:
    service: todo-app-client
  name: todo-app-client
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: todo-app-client


