apiVersion: v1
kind: Service
metadata:
  labels:
    service: todo-app-rp
  name: todo-app-rp
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      port: 80
      targetPort: 80
  selector:
    service: todo-app-rp

