name: Deploy Client
on: [workflow_dispatch]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.DIGITALOCEAN_K8S_CLUSTER_NAME }}
      - name: Apply deployment
        run: kubectl apply -f client/k8s/todo-app-client-deployment.yaml
      - name: Apply service
        run: kubectl apply -f client/k8s/todo-app-client-service.yaml
      - name: Verify deployment
        run: kubectl rollout status deployment/todo-app-client
